<?php

use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BookingController;
use App\Http\Controllers\Api\V1\BookingLifecycleController;
use App\Http\Controllers\Api\V1\BranchController;
use App\Http\Controllers\Api\V1\CourtController;
use App\Http\Controllers\Api\V1\FacilityController;
use App\Http\Controllers\Api\V1\FacilityOperationsController;
use App\Http\Controllers\Api\V1\MembershipPaymentController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OperationsController;
use App\Http\Controllers\Api\V1\OrganizationController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\SportsOperationsController;
use App\Http\Controllers\Api\V1\UserManagementController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::get('health', fn () => response()->json(['data' => ['status' => 'ok']]));
    Route::get('registration/facilities', [\App\Http\Controllers\Api\V1\PlayerRegistrationController::class, 'facilities'])->middleware('throttle:30,1');
    Route::post('auth/register-player', [\App\Http\Controllers\Api\V1\PlayerRegistrationController::class, 'register'])->middleware('throttle:5,1');
    Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:10,1');
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:5,1');
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:5,1');
    Route::post('payments/webhooks/{provider}', [\App\Http\Controllers\Api\V1\CheckoutController::class, 'webhook'])->middleware('throttle:60,1');
    Route::get('openapi.json', fn () => response()->file(base_path('docs/openapi.json'), ['Content-Type' => 'application/json']));

    Route::middleware(['auth:sanctum', \App\Http\Middleware\PlayerAccess::class])->group(function (): void {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::post('auth/change-password', [AuthController::class, 'changePassword']);
        Route::post('auth/refresh-token', [AuthController::class, 'refreshToken']);
        Route::get('auth/sessions', [AuthController::class, 'sessions']);
        Route::delete('auth/sessions/{token}', [AuthController::class, 'destroySession']);
        Route::post('auth/email/verification-notification', [AuthController::class, 'sendVerification'])->middleware('throttle:6,1');
        Route::post('auth/email/verify', [AuthController::class, 'verifyEmail']);
        Route::post('auth/two-factor/setup', [AuthController::class, 'setupTwoFactor']);
        Route::post('auth/two-factor/confirm', [AuthController::class, 'confirmTwoFactor']);
        Route::post('auth/two-factor/disable', [AuthController::class, 'disableTwoFactor']);
        Route::patch('profile', [UserManagementController::class, 'updateProfile']);
        Route::post('profile/avatar', [UserManagementController::class, 'uploadAvatar']);
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::post('notifications/test', [NotificationController::class, 'dispatchTest'])->middleware('role:court-owner|facility-manager');
        Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
        Route::post('notifications/{notification}/read', [NotificationController::class, 'markRead']);
        Route::put('notification-preferences', [NotificationController::class, 'preferences']);

        Route::get('users', [UserManagementController::class, 'index'])->middleware('role:court-owner|facility-manager');
        Route::post('users', [UserManagementController::class, 'store'])->middleware('role:court-owner|facility-manager');
        Route::get('users/{user}', [UserManagementController::class, 'show'])->middleware('role:court-owner|facility-manager');
        Route::patch('users/{user}', [UserManagementController::class, 'update'])->middleware('role:court-owner|facility-manager');
        Route::put('users/{user}/roles', [UserManagementController::class, 'syncRoles'])->middleware('role:court-owner');
        Route::delete('users/{user}', [UserManagementController::class, 'destroy'])->middleware('role:court-owner');
        Route::get('roles', [UserManagementController::class, 'roles'])->middleware('role:court-owner|facility-manager');
        Route::get('permissions', [UserManagementController::class, 'permissions'])->middleware('role:court-owner|facility-manager');
        Route::get('activity-logs', [UserManagementController::class, 'activityLogs'])->middleware('role:court-owner|facility-manager');

        Route::apiResource('organizations', OrganizationController::class)->except('show')->middleware('role:court-owner|facility-manager');
        Route::apiResource('facilities', FacilityController::class)->only(['index', 'store', 'update', 'destroy'])->middleware('role:court-owner|facility-manager');
        Route::get('facilities/{facility}/branches', [BranchController::class, 'index']);
        Route::post('facilities/{facility}/branches', [BranchController::class, 'store'])->middleware('role:court-owner|facility-manager');
        Route::put('branches/{branch}', [BranchController::class, 'update'])->middleware('role:court-owner|facility-manager');
        Route::delete('branches/{branch}', [BranchController::class, 'destroy'])->middleware('role:court-owner|facility-manager');
        Route::get('branches/{branch}/courts', [CourtController::class, 'index']);
        Route::post('branches/{branch}/courts', [CourtController::class, 'store'])->middleware('role:court-owner|facility-manager');
        Route::put('courts/{court}', [CourtController::class, 'update'])->middleware('role:court-owner|facility-manager');
        Route::delete('courts/{court}', [CourtController::class, 'destroy'])->middleware('role:court-owner|facility-manager');

        Route::get('court-types', [FacilityOperationsController::class, 'courtTypes']);
        Route::post('court-types', [FacilityOperationsController::class, 'createCourtType'])->middleware('role:court-owner|facility-manager');
        Route::patch('court-types/{courtType}', [FacilityOperationsController::class, 'updateCourtType'])->middleware('role:court-owner|facility-manager');
        Route::delete('court-types/{courtType}', [FacilityOperationsController::class, 'destroyCourtType'])->middleware('role:court-owner|facility-manager');
        Route::get('branches/{branch}/operating-hours', [FacilityOperationsController::class, 'operatingHours']);
        Route::put('branches/{branch}/operating-hours', [FacilityOperationsController::class, 'replaceOperatingHours'])->middleware('role:court-owner|facility-manager');
        Route::get('branches/{branch}/holidays', [FacilityOperationsController::class, 'holidays']);
        Route::post('branches/{branch}/holidays', [FacilityOperationsController::class, 'createHoliday'])->middleware('role:court-owner|facility-manager');
        Route::delete('holidays/{holiday}', [FacilityOperationsController::class, 'destroyHoliday'])->middleware('role:court-owner|facility-manager');
        Route::get('courts/{court}/maintenance', [FacilityOperationsController::class, 'maintenance']);
        Route::post('courts/{court}/maintenance', [FacilityOperationsController::class, 'createMaintenance'])->middleware('role:court-owner|facility-manager');
        Route::patch('maintenance/{maintenance}', [FacilityOperationsController::class, 'updateMaintenance'])->middleware('role:court-owner|facility-manager');
        Route::get('courts/{court}/pricing-rules', [FacilityOperationsController::class, 'pricingRules']);
        Route::post('courts/{court}/pricing-rules', [FacilityOperationsController::class, 'createPricingRule'])->middleware('role:court-owner|facility-manager');
        Route::patch('pricing-rules/{pricingRule}', [FacilityOperationsController::class, 'updatePricingRule'])->middleware('role:court-owner|facility-manager');
        Route::delete('pricing-rules/{pricingRule}', [FacilityOperationsController::class, 'destroyPricingRule'])->middleware('role:court-owner|facility-manager');

        // Read-only tenant discovery for customers; management routes remain restricted.
        Route::get('booking-facilities', [FacilityController::class, 'index']);
        Route::patch('facilities/{facility}/registration', [\App\Http\Controllers\Api\V1\FacilityOnboardingController::class, 'update'])->middleware('role:court-owner|facility-manager');
        Route::get('courts/{court}/availability', [BookingController::class, 'availability']);
        Route::get('bookings', [BookingController::class, 'index']);
        Route::get('bookings/history', [BookingLifecycleController::class, 'history']);
        Route::post('bookings', [BookingController::class, 'store']);
        Route::post('bookings/walk-in', [BookingController::class, 'walkIn'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('bookings/qr', [BookingController::class, 'qrBooking']);
        Route::get('bookings/{booking}', [BookingController::class, 'show']);
        Route::post('bookings/{booking}/confirm', [BookingController::class, 'confirm'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('bookings/{booking}/cancel', [BookingController::class, 'cancel']);
        Route::post('bookings/waitlist', [BookingLifecycleController::class, 'waitlist']);
        Route::post('bookings/recurring', [BookingLifecycleController::class, 'recurring']);
        Route::patch('bookings/{booking}/reschedule', [BookingLifecycleController::class, 'reschedule']);
        Route::post('bookings/{booking}/refunds', [BookingLifecycleController::class, 'refund'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('bookings/{booking}/qr-code', [BookingLifecycleController::class, 'qr']);
        Route::post('bookings/qr/validate', [BookingLifecycleController::class, 'checkQr'])->middleware('role:court-owner|facility-manager|front-desk');

        Route::get('membership-plans', [OperationsController::class, 'membershipPlans']);
        Route::post('membership-plans', [OperationsController::class, 'createMembershipPlan'])->middleware('role:court-owner|facility-manager');
        Route::patch('membership-plans/{plan}', [MembershipPaymentController::class, 'updatePlan'])->middleware('role:court-owner|facility-manager');
        Route::delete('membership-plans/{plan}', [MembershipPaymentController::class, 'destroyPlan'])->middleware('role:court-owner|facility-manager');
        Route::get('memberships', [OperationsController::class, 'memberships']);
        Route::post('memberships', [OperationsController::class, 'activateMembership'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('memberships/{membership}', [MembershipPaymentController::class, 'showMembership']);
        Route::post('memberships/{membership}/freeze', [MembershipPaymentController::class, 'freeze'])->middleware('role:court-owner|facility-manager');
        Route::post('memberships/{membership}/unfreeze', [MembershipPaymentController::class, 'unfreeze'])->middleware('role:court-owner|facility-manager');
        Route::post('memberships/{membership}/cancel', [MembershipPaymentController::class, 'cancelMembership'])->middleware('role:court-owner|facility-manager');
        Route::post('memberships/{membership}/renew', [MembershipPaymentController::class, 'renew'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('memberships/{membership}/cards', [MembershipPaymentController::class, 'createCard'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('memberships/{membership}/sessions/use', [MembershipPaymentController::class, 'useSession'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('memberships/{membership}/session-usage', [MembershipPaymentController::class, 'sessionUsage']);

        Route::get('coaches', [OperationsController::class, 'coaches']);
        Route::post('coaches', [OperationsController::class, 'createCoach'])->middleware('role:court-owner|facility-manager');
        Route::patch('coaches/{coach}', [SportsOperationsController::class, 'updateCoach'])->middleware('role:court-owner|facility-manager');
        Route::delete('coaches/{coach}', [SportsOperationsController::class, 'destroyCoach'])->middleware('role:court-owner|facility-manager');
        Route::get('coaches/{coach}/availability', [SportsOperationsController::class, 'coachAvailability']);
        Route::put('coaches/{coach}/availability', [SportsOperationsController::class, 'replaceCoachAvailability'])->middleware('role:court-owner|facility-manager');
        Route::get('coaches/{coach}/revenue', [SportsOperationsController::class, 'coachRevenue'])->middleware('role:court-owner|facility-manager|coach');
        Route::get('coaching-sessions', [SportsOperationsController::class, 'coachingSessions']);
        Route::post('coaching-sessions', [SportsOperationsController::class, 'createCoachingSession']);
        Route::post('coaching-sessions/{session}/complete', [SportsOperationsController::class, 'completeCoachingSession'])->middleware('role:court-owner|facility-manager|front-desk|coach');
        Route::post('coaching-sessions/{session}/cancel', [SportsOperationsController::class, 'cancelCoachingSession']);
        Route::get('inventory-items', [OperationsController::class, 'inventory']);
        Route::post('inventory-items', [OperationsController::class, 'createInventory'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::patch('inventory-items/{inventoryItem}', [SportsOperationsController::class, 'updateInventory'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('rentals', [OperationsController::class, 'rentals']);
        Route::post('rentals', [OperationsController::class, 'createRental'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('rentals/overdue', [SportsOperationsController::class, 'overdueRentals'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('rentals/{rental}', [SportsOperationsController::class, 'showRental']);
        Route::post('rentals/{rental}/extend', [SportsOperationsController::class, 'extendRental'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('rentals/{rental}/close', [SportsOperationsController::class, 'closeRental'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('rentals/{rental}/return', [OperationsController::class, 'returnRental'])->middleware('role:court-owner|facility-manager|front-desk');

        Route::get('tournaments', [OperationsController::class, 'tournaments']);
        Route::post('tournaments', [OperationsController::class, 'createTournament'])->middleware('role:court-owner|facility-manager|event-organizer');
        Route::get('tournaments/{tournament}', [SportsOperationsController::class, 'showTournament']);
        Route::patch('tournaments/{tournament}', [SportsOperationsController::class, 'updateTournament'])->middleware('role:court-owner|facility-manager|event-organizer');
        Route::post('tournaments/{tournament}/registrations', [OperationsController::class, 'registerTournament']);
        Route::get('tournaments/{tournament}/registrations', [SportsOperationsController::class, 'registrations']);
        Route::post('tournaments/{tournament}/registrations/{registration}/cancel', [SportsOperationsController::class, 'cancelRegistration']);
        Route::get('tournaments/{tournament}/matches', [SportsOperationsController::class, 'matches']);
        Route::post('tournaments/{tournament}/matches', [SportsOperationsController::class, 'createMatch'])->middleware('role:court-owner|facility-manager|event-organizer');
        Route::patch('tournament-matches/{match}', [SportsOperationsController::class, 'updateMatch'])->middleware('role:court-owner|facility-manager|event-organizer');
        Route::get('payments', [OperationsController::class, 'payments'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('payments', [OperationsController::class, 'recordPayment'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('payments/intents', [\App\Http\Controllers\Api\V1\CheckoutController::class, 'create'])->middleware('throttle:10,1');
        Route::get('bookings/{booking}/payment-status', [\App\Http\Controllers\Api\V1\CheckoutController::class, 'status'])->middleware('throttle:30,1');
        Route::get('payments/providers', [MembershipPaymentController::class, 'providers']);
        Route::post('payments/{payment}/refunds', [MembershipPaymentController::class, 'refund'])->middleware('role:court-owner|facility-manager');
        Route::get('payments/{payment}/invoice', [MembershipPaymentController::class, 'invoice']);
        Route::get('payments/reconciliation/summary', [MembershipPaymentController::class, 'reconciliation'])->middleware('role:court-owner|facility-manager');
        Route::post('check-ins/qr', [OperationsController::class, 'qrCheckIn'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::post('check-ins', [OperationsController::class, 'checkIn'])->middleware('role:court-owner|facility-manager|front-desk');
        Route::get('reports/dashboard', [OperationsController::class, 'dashboard'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/revenue', [ReportController::class, 'revenue'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/occupancy', [ReportController::class, 'occupancy'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/peak-hours', [ReportController::class, 'peakHours'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/court-utilization', [ReportController::class, 'courtUtilization'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/membership-sales', [ReportController::class, 'membershipSales'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/coach-revenue', [ReportController::class, 'coachRevenue'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/tournament-revenue', [ReportController::class, 'tournamentRevenue'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/rental-revenue', [ReportController::class, 'rentalRevenue'])->middleware('role:court-owner|facility-manager');
        Route::get('reports/refunds', [ReportController::class, 'refunds'])->middleware('role:court-owner|facility-manager');
    });
});
